### PR TITLE
Setup physics and drivetrain for encoder

### PR DESCRIPTION
**Pull request by brendanburkhart**

### CODE REVIEW

**Comment by brendanburkhart** [comment]
We're going to have to add some sort of scaling ratio between wheel revolutions and meters for this to work properly irl.

**Review by calebeby — CHANGES_REQUESTED** [review]
Well before the scaling was pretty good on the sim.
But now it's not.

What we want is in forward mode, the robot should drive forward 30 feet, which means that the front of the robot should be 6 feet past the midline. That means there should be 1 robot-width between the midline and the back of the robot. Can you get some multiplier for the sim so that we can have (relatively) accurate simulation?

**Comment by brendanburkhart** [comment]
Yes, but as I said the drive train is going to need its own multiplier for the wheel size. So whatever I add will be a temporary fix.

**Comment by calebeby** [comment]
Yup

**Comment by brendanburkhart** [comment]
How close to 30 feet do you want it? I'm assuming each square is one foot, is that right?

**Comment by calebeby** [comment]
Yes. Just approximately. Like I said, there should be one robot-width between the robot and the line

Our wheels are 6"
The circumference in inches is 6pi

so, 0.1524 meters per revolution

**Comment by brendanburkhart** [comment]
Shouldn't that be 0.1524 * pi?

**Comment by calebeby** [comment]
Yes my bad

**Review by calebeby — APPROVED** [review]

**Comment by brendanburkhart** [comment]
I got it to drive pretty much exactly 30 feet (~29.99), but you should double check all the scaling both in physics and in the drive train. There's a pretty good chance I messed up somewhere.

**Pull request merged**
